name: quotes_for_you
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  http: ^1.2.0
  provider: ^6.1.1
  share_plus: ^4.5.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans.ttf
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand.ttf
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab.ttf
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SanFrancisco.otf
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/TimesNewRoman.ttf
